export const StrenghtExercise = [
    { name: '3-pos Clean' },
    { name: '3-pos Snatch' },
    { name: 'Back Squat' },
    { name: 'Front Squat' },
    { name: 'Deadlift' },
    { name: 'Low Blocks Deadlift' },
    { name: 'Deficit Deadlift' },
    { name: 'Deficit Snatch Grip Deadlift' },
    { name: 'Overhead Squat' },
    { name: 'Snatch Balance' },
    { name: 'Heaving Snatch Balance' },
    { name: 'Strict Press' },
    { name: 'Push Press' },
    { name: 'Push Jerk' },
    { name: 'Split Jerk' },
    { name: 'Snatch Grip Press' },
    { name: 'Snatch' },
    { name: 'Hang Snatch' },
    { name: 'Hang Snatch BTK' },
    { name: 'High Hang Snatch' },
    { name: 'Clean & Jerk' },
    { name: 'Clean' },
    { name: 'Hang Clean' },
    { name: 'Hang Clean BTK' },
    { name: 'High Hang Clean' },
    { name: 'Clean Pull' },
    { name: 'Clean High Pull' },
    { name: 'Snatch Pull' },
    { name: 'Snatch High Pull' },
    { name: 'Clean Grip Deadlift' },
    { name: 'Snatch Deadlift' },
    { name: 'High Blocks Snatch' },
    { name: 'Low Blocks Snatch' },
    { name: 'High Blocks Clean' },
    { name: 'Low Blocks Clean' },
    { name: 'High Blocks Clean & Jerk' },
    { name: 'Low Blocks Clean & Jerk' },
    { name: 'Sott Press' },
    { name: 'Clean Grip Sott Press' },
    { name: 'Bench Press' },

    { name: 'GHD HyperExtension' },
    { name: 'GHD Situp' },

    { name: 'Strict Pullups' },
    { name: 'Butterfly Pullups' },
    { name: 'Kipping Pullups' },
    { name: 'Chest to Bar' },
    { name: 'Kipping Chest to Bar' },
    { name: 'Butterfly Chest to Bar' },
    { name: 'Parallette Dips' },
    { name: 'Ring Dips' },
    { name: 'Kipping Ring Dips' },
    { name: 'Strict Ring Muscle Ups' },
    { name: 'Kipping Ring Muscle Ups' },
    { name: 'Bar Muscle Ups' },
    { name: 'Toes To Bar' },
    { name: 'Strict Handstand Pushups' },
    { name: 'Kipping Handstand Pushups' },
]