export const StrenghtExercise = [
    { name: '3-pos Clean', category: "wl" },
    { name: '3-pos Snatch', category: "wl" },
    { name: 'Back Squat', category: "wl" },
    { name: 'Bench Press', category: "wl" },
    { name: 'Bench Press DB', category: "wl" },
    { name: 'Clean', category: "wl" },
    { name: 'Clean off High Blocks', category: "wl" },
    { name: 'Clean off Low Blocks ', category: "wl" },
    { name: 'Clean & Jerk', category: "wl" },
    { name: 'Clean & Jerk off High Blocks', category: "wl" },
    { name: 'Clean & Jerk off Low Blocks', category: "wl" },
    { name: 'Clean High Pull', category: "wl" },
    { name: 'Clean Pull', category: "wl" },
    { name: 'Clean Grip Sott Press', category: "wl" },
    { name: 'Deadlift', category: "wl" },
    { name: 'Deadlift Clean Grip', category: "wl" },
    { name: 'Deadlift Snatch Grip', category: "wl" },
    { name: 'Deficit Deadlift', category: "wl" },
    { name: 'Deficit Snatch Grip Deadlift', category: "wl" },
    { name: 'Hang Clean', category: "wl" },
    { name: 'Hang Clean BTK', category: "wl" },
    { name: 'Hang Snatch', category: "wl" },
    { name: 'Hang Snatch BTK', category: "wl" },
    { name: 'High Blocks Snatch', category: "wl" },
    { name: 'High Hang Snatch', category: "wl" },
    { name: 'High Hang Clean', category: "wl" },
    { name: 'Overhead Squat', category: "wl" },
    { name: 'Front Squat', category: "wl" },
    { name: 'Low Blocks Deadlift', category: "wl" },
    { name: 'Low Blocks Snatch', category: "wl" },
    { name: 'Push Jerk', category: "wl" },
    { name: 'Push Press', category: "wl" },
    { name: 'Reverse hyper', category: "wl" },
    { name: 'Split Jerk', category: "wl" },
    { name: 'Snatch Balance', category: "wl" },
    { name: 'Snatch Balance Heaving', category: "wl" },
    { name: 'Strict Press BB', category: "wl" },
    { name: 'Strict Press BB BTK', category: "wl" },
    { name: 'Strict Press DB', category: "wl" },
    { name: 'Strict Press Snatch grip BTK', category: "wl" },
    { name: 'Snatch High Pull', category: "wl" },
    { name: 'Snatch Pull', category: "wl" },
    { name: 'Snatch', category: "wl" },
    { name: 'Sott Press', category: "wl" },

    { name: 'Bar Muscle Ups', category: "gym" },
    { name: 'Chest to Bar Strict', category: "gym" },
    { name: 'Chest to Bar Butterfly', category: "gym" },
    { name: 'Chest to Bar Kipping', category: "gym" },
    { name: 'GHD HyperExtension', category: "gym" },
    { name: 'GHD Situp', category: "gym" },
    { name: 'Handstand Hold', category: "gym" },
    { name: 'Handstand Pushups Kipping', category: "gym" },
    { name: 'Handstand Pushups Strict', category: "gym" },
    { name: 'Handstand Walk', category: "gym" },
    { name: 'L-sit', category: "gym" },
    { name: 'Parallette Dips Strict', category: "gym" },
    { name: 'Parallette Dips Kipping', category: "gym" },
    { name: 'Pullups Butterfly', category: "gym" },
    { name: 'Pullups Kipping', category: "gym" },
    { name: 'Pullups Strict', category: "gym" },
    { name: 'Ring Dips Strict', category: "gym" },
    { name: 'Ring Dips Kipping', category: "gym" },
    { name: 'Ring Muscle Ups Strict', category: "gym" },
    { name: 'Ring Muscle Ups Kipping', category: "gym" },
    { name: 'Toes To Bar Strict', category: "gym" },
    { name: 'Toes To Bar Kipping', category: "gym" },
    { name: 'Toes To Ring', category: "gym" },
]

export const EnduranceWorkouts = [
    { name: "Bike 20' max cal" },
    { name: 'Row 5k for time' },
]

export const BenchmarkWorkouts = [
    { name: 'Bergeron Beep Test' },
]
