export const StrenghtExercise = [
    { name: 'Back Squat' },
    { name: 'Front Squat' },
    { name: 'Deadlift' },
    { name: 'Low Blocks Deadlift' },
    { name: 'Deficit Deadlift' },
    { name: 'OverHead Squat' },
    { name: 'Snatch Balance' },
    { name: 'Heaving Snatch Balance' },
    { name: 'Strict Press' },
    { name: 'Push Press' },
    { name: 'Push Jerk' },
    { name: 'Split Jerk' },
    { name: 'Snatch Grip Press' },
    { name: 'Snatch' },
    { name: 'Clean & Jerk' },
    { name: 'Clean' },
    { name: 'Clean Grip Deadlift' },
    { name: 'Snatch Deadlift' },
    { name: 'High Blocks Snatch' },
    { name: 'Low Blocks Snatch' },
    { name: 'High Blocks Clean' },
    { name: 'Low Blocks Clean' },
    { name: 'High Blocks Clean & Jerk' },
    { name: 'Low Blocks Clean & Jerk' },
    { name: 'Sott Press' },

    { name: 'Pullups' },
    { name: 'Butterfly Pullups' },
    { name: 'Kipping Pullups' },
    { name: 'Chest to Bar' },
    { name: 'Kipping Chest to Bar' },
    { name: 'Butterfly Chest to Bar' },
    { name: 'Parallette Dips' },
    { name: 'Ring Dips' },
    { name: 'Ring Muscle Ups' },
    { name: 'Bar Muscle Ups' },
    { name: 'Toes To Bar' },

]